Include("\\script\\lib\\player.lua")
-- Include("\\script\\global\\bil4i3n\\bil4i3n_tasklist.lua")

Bil_TaskID = 
{
	[1] = {BilTaskID = {5999}, BilDesc = "NhËn hç trî t©n thñ",},
	[2] = {BilTaskID = {5998}, BilDesc = "L­u th«ng tin nh©n vËt ®ang Offlive d¹ng ñy th¸c",},
	[3] = {BilTaskID = {5997}, BilDesc = "KiÓm tra chÕ ®é cho phÐp Chat víi GameMaster",},
	[4] = {BilTaskID = {5996}, BilDesc = "L­u th«ng tin nhËn bé Kü n¨ng m«n ph¸i",},
	[5] = {BilTaskID = {5995}, BilDesc = "XuÊt s­, hµnh tÈu giang hå",},
	[6] = {BilTaskID = {5994}, BilDesc = "§æi tªn nh©n vËt",},
	[7] = {BilTaskID = {5993}, BilDesc = "L­u ®¼ng cÊp kü n¨ng1 - 90 khi chuyÓn ph¸i",},
	[8] = {BilTaskID = {5992}, BilDesc = "L­u ®¼ng cÊp kü n¨ng2 - 90 khi chuyÓn ph¸i",},
	[9] = {BilTaskID = {5991}, BilDesc = "L­u ®¼ng cÊp kü n¨ng3 - 90 khi chuyÓn ph¸i",},
	[10] = {BilTaskID = {5990}, BilDesc = "L­u ®¼ng cÊp kü n¨ng 120 khi chuyÓn ph¸i",},
	[11] = {BilTaskID = {5989}, BilDesc = "Cho phÐp chuyÓn ph¸i ®Õn m«n ph¸i kh¸c",},
	[12] = {BilTaskID = {5988}, BilDesc = "Sè lÇn chuyÓn ®æi giíi tÝnh",},
	[13] = {BilTaskID = {0000}, BilDesc = "(! - -)",},
	[14] = {BilTaskID = {5987}, BilDesc = "Sè lÇn ®iÓm danh h»ng ngµy",},
	[15] = {BilTaskID = {5986}, BilDesc = "Thêi gian cuèi cïng ®iÓm danh h»ng ngµy",},
	[16] = {BilTaskID = {5985}, BilDesc = "Tæng thêi gian online trªn m¹ng",},
	[17] = {BilTaskID = {5984}, BilDesc = "Tæng sè lÇn nhËn th­ëng Online trong ngµy",},
	[18] = {BilTaskID = {5983}, BilDesc = "Thêi gian cuèi cïng (ngµy) nhËn phÇn th­ëng Online",},
	[19] = {BilTaskID = {5982}, BilDesc = "Tæng sè khiªu chiÕn lÖnh ®· nép",},
	[20] = {BilTaskID = {5981}, BilDesc = "Sè trËn th¾ng trong Hoa S¬n §¹i ChiÕn",},
	[21] = {BilTaskID = {5980}, BilDesc = "Sè ng­êi h¹ gôc ®­îc trong Hoa S¬n §¹i ChiÕn",},
	[22] = {BilTaskID = {5979}, BilDesc = "Sè l­îng NhÝm bÐo ph× ®· s¨n trong ngµy",},
	[23] = {BilTaskID = {5979}, BilDesc = "(! - -)",},
	[24] = {BilTaskID = {5977}, BilDesc = "Tæng l­îng NhÝm bÐo ph× ®· s¨n",},
	[25] = {BilTaskID = {5976}, BilDesc = "Thêi gian cuèi cïng s¨n NhÝm bÐo ph×",},
	[26] = {BilTaskID = {5975}, BilDesc = "Tæng sè lÇn hoµn thµnh B¶o tµng viªm ®Õ",},
	[27] = {BilTaskID = {5974}, BilDesc = "Thêi gian cËp nhËt d÷ liÖu thø h¹ng giang hå gÇn ®©y nhÊt",},
	[28] = {BilTaskID = {5973}, BilDesc = "Thø h¹ng giang hå",},
	[29] = {BilTaskID = {5972}, BilDesc = "Thêi gian lÊy d÷ liÖu Thø h¹ng giang hå gÇn ®©y nhÊt",},
	[30] = {BilTaskID = {5971}, BilDesc = "Thêi gian nhËn th­ëng ®ua TOP cao thñ",},
	[31] = {BilTaskID = {5970}, BilDesc = "Mµu ch÷ ng­êi ch¬i khi bÞ ®­a lªn ®¶o",},
	[32] = {BilTaskID = {5969}, BilDesc = "L­u Timer ID cña ng­êi ch¬i dïng ®Ó Active Title",},
	[33] = {BilTaskID = {5968}, BilDesc = "Tæng ®Ö tö mµ ng­êi ch¬i ®· thu nhËn",},
	[34] = {BilTaskID = {5967}, BilDesc = "§­a nh©n vËt míi khëi t¹o vÒ ®iÓm chØ ®Þnh",},
	[35] = {BilTaskID = {5966}, BilDesc = "Nh©n vËt cã tham gia ®ua top hay kh«ng",},
	[36] = {BilTaskID = {5965}, BilDesc = "§· nhËn th­ëng 3 TTL tham gia ®ua TOP hay ch­a",},
	[37] = {BilTaskID = {5964}, BilDesc = "Sè lÇn dïng b¸nh chay",},
	[38] = {BilTaskID = {5963}, BilDesc = "Sè lÇn dïng giá hoa hång",},
	[39] = {BilTaskID = {5962}, BilDesc = "Sè lÇn dïng b«ng hång cµi ¸o",},
	[40] = {BilTaskID = {5961}, BilDesc = "Sè lÇn dïng hép lÔ vËt tiÓu",},
	[41] = {BilTaskID = {5960}, BilDesc = "Sè lÇn dïng hép lÔ vËt ®¹i",},
	[42] = {BilTaskID = {5959}, BilDesc = "Sè lÇn dïng hoa hång",},
	[43] = {BilTaskID = {5958}, BilDesc = "Sè lÇn dïng tói ®­êng",},
	[44] = {BilTaskID = {5957}, BilDesc = "Th­ëng mèc hoa hång",},
	[45] = {BilTaskID = {5956}, BilDesc = "Th­ëng mèc tói ®­êng",},
	[46] = {BilTaskID = {5955}, BilDesc = "Th­ëng thµnh chñ cña C«ng thµnh chiÕn",},
	[47] = {BilTaskID = {5954}, BilDesc = "Mua hiÖu øng håi m¸u, mana trong 1 ngµy cho ng­êi trªn cÊp 140",},
	[48] = {BilTaskID = {5953}, BilDesc = "§iÓm tÝch lòy n©ng cÊp chiÕn m·",},
	[49] = {BilTaskID = {5952}, BilDesc = "TÝch lòy n©ng cÊp §Ých L«",},
	[50] = {BilTaskID = {5951}, BilDesc = "TÝch lòy n©ng cÊp TuyÖt ¶nh",},
	[51] = {BilTaskID = {5950}, BilDesc = "TÝch lòy n©ng cÊp ¤ v©n ®¹p tuyÕt",},
	[52] = {BilTaskID = {5949}, BilDesc = "TÝch lòy n©ng cÊp XÝch Thè",},
	[53] = {BilTaskID = {5948}, BilDesc = "TÝch lòy n©ng cÊp ChiÕu D¹",},
	[54] = {BilTaskID = {5947}, BilDesc = "TÝch lòy n©ng cÊp Phi V©n",},
	[55] = {BilTaskID = {5946}, BilDesc = "TÝch lòy n©ng cÊp B«n Tiªu",},
	[56] = {BilTaskID = {5945}, BilDesc = "__Ver_HKMP_TÝch lòy n©ng cÊp Trang bÞ hoµng kim tõ Thanh C©u ®Õn Minh ph­îng",},
	[57] = {BilTaskID = {5944}, BilDesc = "__Ver_HKMP_TÝch lòy n©ng cÊp Trang søc vµ ngò hµnh Ên",},
	[58] = {BilTaskID = {5943}, BilDesc = "__Ver_HKMP_TÝch lòy thêi gian Online",},
	[59] = {BilTaskID = {5942}, BilDesc = "__Ver_HKMP_Thêi gian b¾t ®Çu tÝnh Online",},
	[60] = {BilTaskID = {5941}, BilDesc = "__Ver_HKMP_L­u tr÷ thêi gian Online trong ngµy",},
	[61] = {BilTaskID = {5940}, BilDesc = "__Ver_HKMP_KiÓm tra ®· nhËn th­ëng Online hay ch­a",},
	[62] = {BilTaskID = {5939}, BilDesc = "__Ver_HKMP_NhËn th­ëng h»ng ngµy",},
	[63] = {BilTaskID = {5938}, BilDesc = "Sè lÇn n©ng cÊp thÊt b¹i XÝch Long C©u",},
	[64] = {BilTaskID = {5937}, BilDesc = "Sè lÇn n©ng cÊp thÊt b¹i Siªu Quang",},
	[65] = {BilTaskID = {5936}, BilDesc = "__Ver_HKMP_KiÓm tra xem ®· set tr¹ng th¸i phi chiÕn ®Êu khi ®ua top ch­a",},
	[66] = {BilTaskID = {5935}, BilDesc = "__Ver_HKMP_Tæng sè lÇn tham gia tÝnh n¨ng C¶nh Kü Tr­êng trong ngµy!",},
	[67] = {BilTaskID = {5934}, BilDesc = "__Ver_HKMP_Ngµy cuèi cïng tham gia tÝnh n¨ng C¶nh kü tr­êng!",},
	[68] = {BilTaskID = {5933}, BilDesc = "Ngµy tham gia tÝnh n¨ng Viªm ®Õ lÇn cuèi cïng",},
	[69] = {BilTaskID = {5932}, BilDesc = "Sè lÇn tham gia tÝnh n¨ng Viªm ®Õ trong ngµy",},
	[70] = {BilTaskID = {5931}, BilDesc = "Hç trî cho t©n thñ lÇn ®Çu t¹o nh©n vËt",},
	[71] = {BilTaskID = {5930}, BilDesc = "N¹p thÎ - gi¸ trÞ tiÒn ®ång cuèi cïng cßn trong sql",},
	[72] = {BilTaskID = {5929}, BilDesc = "N¹p thÎ - tæng sè lÇn ®· n¹p, tÝnh mçi lÇn ®¨ng nhËp l¹i ®Ó kiÓm tra thÎ, kh«ng thÓ tÝnh tæng sè thÎ n¹p",},
	[73] = {BilTaskID = {5928}, BilDesc = "Phóc lîi - Ngµy cuèi cïng nhËn th­ëng n¹p thÎ lÇn ®Çu",},
	[74] = {BilTaskID = {5927}, BilDesc = "Phóc lîi - Tæng sè lÇn nhËn th­ëng n¹p thÎ lÇn ®Çu",},
	[75] = {BilTaskID = {5926}, BilDesc = "Phóc lîi - PhÇn th­ëng n¹p thÎ lÇn ®Çu trong ngµy 1",},
	[76] = {BilTaskID = {5925}, BilDesc = "Phóc lîi - PhÇn th­ëng n¹p thÎ lÇn ®Çu trong ngµy 2",},
	[77] = {BilTaskID = {5924}, BilDesc = "Phóc lîi - PhÇn th­ëng n¹p thÎ lÇn ®Çu trong ngµy 3",},
	[78] = {BilTaskID = {5923}, BilDesc = "Phóc lîi - PhÇn th­ëng n¹p thÎ lÇn ®Çu trong ngµy 4",},
	[79] = {BilTaskID = {5922}, BilDesc = "Phóc lîi - PhÇn th­ëng n¹p thÎ lÇn ®Çu trong ngµy 5",},
	[80] = {BilTaskID = {5921}, BilDesc = "Phóc lîi - PhÇn th­ëng n¹p thÎ lÇn ®Çu trong ngµy 6",},
	[81] = {BilTaskID = {5920}, BilDesc = "Phóc lîi - Ngµy cuèi cïng t¹o míi phÇn th­ëng n¹p thÎ lÇn ®Çu",},
	[82] = {BilTaskID = {5919}, BilDesc = "N¹p thÎ - L­u gi÷ thêi gian cña thÎ n¹p cuèi cïng",},
	[83] = {BilTaskID = {5918}, BilDesc = "Phóc lîi - ThÇn m·: tæng tÝch lòy hiÖn cã",},
	[84] = {BilTaskID = {5917}, BilDesc = "Phóc lîi - ThÇn m·: sè mèc ®· nhËn",},
	[85] = {BilTaskID = {5916}, BilDesc = "Phóc lîi - Hång ¶nh: tæng tÝch lòy hiÖn cã",},
	[86] = {BilTaskID = {5915}, BilDesc = "Phóc lîi - Hång ¶nh: sè mèc ®· nhËn",},
	[87] = {BilTaskID = {5914}, BilDesc = "Phóc lîi - Nhu t×nh: tæng tÝch lòy hiÖn cã",},
	[88] = {BilTaskID = {5913}, BilDesc = "Phóc lîi - Nhu t×nh: sè mèc ®· nhËn",},
	[89] = {BilTaskID = {5912}, BilDesc = "Phóc lîi - HiÖp cèt: tæng tÝch lòy hiÖn cã",},
	[90] = {BilTaskID = {5911}, BilDesc = "Phóc lîi - HiÖp cèt: sè mèc ®· nhËn",},
	[91] = {BilTaskID = {5910}, BilDesc = "Phóc lîi - §Þnh quèc: tæng tÝch lòy hiÖn cã",},
	[92] = {BilTaskID = {5909}, BilDesc = "Phóc lîi - §Þnh quèc: sè mèc ®· nhËn",},
	[93] = {BilTaskID = {5908}, BilDesc = "Phóc lîi - An bang: tæng tÝch lòy hiÖn cã",},
	[94] = {BilTaskID = {5907}, BilDesc = "Phóc lîi - An bang: sè mèc ®· nhËn",},
	[95] = {BilTaskID = {5906}, BilDesc = "N¹p thÎ - Tæng gi¸ trÞ tiÒn ®ång ®· n¹p vµo nh©n vËt",},
	[96] = {BilTaskID = {5905}, BilDesc = "NV T©n Thñ - Ghi nhËn mèc nhiÖm vô ®ang thùc thi",},
	[97] = {BilTaskID = {5904}, BilDesc = "Auto Chat - T¾t më kªnh Phô cËn",},
	[98] = {BilTaskID = {5903}, BilDesc = "Auto Chat - T¾t më kªnh Thµnh thÞ",},
	[99] = {BilTaskID = {5902}, BilDesc = "Auto Chat - T¾t më kªnh ThÕ giíi",},
	[100] = {BilTaskID = {5901}, BilDesc = "Auto Chat - T¾t më kªnh Bang héi",},
	[101] = {BilTaskID = {5900}, BilDesc = "Auto Chat - T¾t më kªnh M«n ph¸i",},
	[102] = {BilTaskID = {5899}, BilDesc = "GiftCode - L­u th«ng tin ng­êi ch¬i nhËn th­ëng code t©n thñ",},
	[103] = {BilTaskID = {5898}, BilDesc = "NhiÖm vô cÊp 90 - ThiÕu l©m",},
	[104] = {BilTaskID = {5897}, BilDesc = "NhiÖm vô cÊp 90 - Thiªn v­¬ng",},
	[105] = {BilTaskID = {5896}, BilDesc = "NhiÖm vô cÊp 90 - §­êng m«n",},
	[106] = {BilTaskID = {5895}, BilDesc = "NhiÖm vô cÊp 90 - Ngò ®éc",},
	[107] = {BilTaskID = {5894}, BilDesc = "NhiÖm vô cÊp 90 - Nga my",},
	[108] = {BilTaskID = {5893}, BilDesc = "NhiÖm vô cÊp 90 - Thóy yªn",},
	[109] = {BilTaskID = {5892}, BilDesc = "NhiÖm vô cÊp 90 - C¸i bang",},
	[110] = {BilTaskID = {5891}, BilDesc = "NhiÖm vô cÊp 90 - Thiªn nhÉn",},
	[111] = {BilTaskID = {5890}, BilDesc = "NhiÖm vô cÊp 90 - Vâ ®ang",},
	[112] = {BilTaskID = {5889}, BilDesc = "NhiÖm vô cÊp 90 - C«n l«n",},
	[114] = {BilTaskID = {5888}, BilDesc = "Häc khinh c«ng chç vâ s­",},
	[115] = {BilTaskID = {5887}, BilDesc = "ñy th¸c - Thêi gian cßn l¹i",},
	[116] = {BilTaskID = {5886}, BilDesc = "ñy th¸c - §­a nh©n vËt vµo tr¹ng th¸i ñy th¸c nhËn exp, GetGameTime",},
	[117] = {BilTaskID = {5885}, BilDesc = "Hç trî t©n thñ, thêi gian nhËn m¸u cuèi cïng",},
	[118] = {BilTaskID = {5884}, BilDesc = "Hç trî l­u phiªn lµm viÖc cña GameMaster - Multigamesv",},
	[119] = {BilTaskID = {5883}, BilDesc = "Söa lçi thµnh lËp bang héi thÊt b¹i nh­ng bÞ trõ c¸c vËt phÈm vµ tiÒn v¹n",},
	[120] = {BilTaskID = {5882}, BilDesc = "Ph¸t th­ëng tham gia Event Tèng kim cho Team Sp tæ chøc",},
	[121] = {BilTaskID = {5881}, BilDesc = "CÊm ch¸t nh©n vËt trong thêi gian chØ ®Þnh",},
	[122] = {BilTaskID = {5880}, BilDesc = "Event-QuocKhanh-02_09 Sè lÇn sö dông Bã hoa quèc kh¸nh",},
	[123] = {BilTaskID = {5879}, BilDesc = "Event-QuocKhanh-02_09 Sè lÇn sö dông Giá hoa quèc kh¸nh",},
	[124] = {BilTaskID = {5878}, BilDesc = "Ph¸t th­ëng Code T©n thñ ®ît 2",},
	[125] = {BilTaskID = {5877}, BilDesc = "Bang héi - Thêi gian chuyÓn ®æi phe ph¸i cuèi cïng",},
	[126] = {BilTaskID = {5876}, BilDesc = "Tèng Kim - SJ_PointExChange: Ngµy ®æi cuèi cïng",},
	[127] = {BilTaskID = {5875}, BilDesc = "Tèng Kim - Tæng ®iÓm exp ®· ®æi",},
	[128] = {BilTaskID = {5874}, BilDesc = "Huy Hoµng Qu¶ - Thêi gian cuèi cïng sö dông Huy Hoµng Qu¶",},
	[129] = {BilTaskID = {5873}, BilDesc = "C©u C¸: Thêi gian cuèi cïng nhËn ®­îc exp",},
	[130] = {BilTaskID = {5872}, BilDesc = "C©u C¸: Tæng Exp ®· nhËn ®­îc trong ngµy",},
	[131] = {BilTaskID = {5871}, BilDesc = "Event-TrungThu-Thang8: Tæng b¸nh §Ëu xanh",},
	[132] = {BilTaskID = {5870}, BilDesc = "Event-TrungThu-Thang8: Tæng b¸nh Nh©n thÞt",},
	[133] = {BilTaskID = {5869}, BilDesc = "Event-TrungThu-Thang8: B¸nh B»ng H÷u",},
	[134] = {BilTaskID = {5868}, BilDesc = "Event-TrungThu-Thang8: B¸nh H¹nh Phóc",},
	[135] = {BilTaskID = {5867}, BilDesc = "Event-TrungThu-Thang8 - Hoa §¨ng: Ngµy cuèi cïng tham gia tr¶ lêi hoa ®¨ng",},
	[136] = {BilTaskID = {5866}, BilDesc = "Event-TrungThu-Thang8 - Hoa §¨ng: Tæng sè l­îng hoa ®¨ng ®· më",},
	[137] = {BilTaskID = {5865}, BilDesc = "Event-TrungThu-Thang8 - Hoa §¨ng: Sè l­îng c©u tr¶ lêi ®óng liªn tiÕp",},
}

bil_TaskTemp = {
	[1] = {bil_nId = {255}, bil_sDesc = "Verify Client - KiÓm tra Client khi ng­êi ch¬i ®¨ng nhËp vµo game!"},
	[2] = {bil_nId = {254}, bil_sDesc = "Auto Chat - KiÓm tra ®· khëi ®éng Timer hay ch­a"},
	[3] = {bil_nId = {253}, bil_sDesc = "Auto Chat - Vßng lÆp Timer"},
	[4] = {bil_nId = {252}, bil_sDesc = "Auto Chat - Sè lÇn ®· rao kªnh M«n ph¸i"},
	[5] = {bil_nId = {251}, bil_sDesc = "Auto Chat - Sè lÇn ®· rao kªnh Bang héi"},
	[6] = {bil_nId = {250}, bil_sDesc = "Auto Chat - Sè lÇn ®· rao kªnh ThÕ giíi"},
	[7] = {bil_nId = {249}, bil_sDesc = "Auto Chat - Sè lÇn ®· rao kªnh Thµnh thÞ"},
	[8] = {bil_nId = {248}, bil_sDesc = "Auto Chat - Sè lÇn ®· rao kªnh Phô cËn"},
}

bil_LadderId = {
	[01] = {n_Id = {10500}, s_Desc = "§ua TOP - KiÓm tra th«ng b¸o trªn kªnh thÕ giíi!"},
	[02] = {n_Id = {10499}, s_Desc = "Verify Client - Danh s¸ch c¸c tµi kho¶n sö dông Client kh«ng hîp lÖ!"},
	[03] = {n_Id = {10498}, s_Desc = "Verify Client - Danh s¸ch c¸c tµi kho¶n sö dông Client kh«ng hîp lÖ!"},
	[04] = {n_Id = {10497}, s_Desc = "Verify Client - Danh s¸ch c¸c tµi kho¶n sö dông Client kh«ng hîp lÖ!"},
	[05] = {n_Id = {10496}, s_Desc = "Verify Client - Danh s¸ch c¸c tµi kho¶n sö dông Client kh«ng hîp lÖ!"},
	[06] = {n_Id = {10495}, s_Desc = "Verify Client - Danh s¸ch c¸c tµi kho¶n sö dông Client kh«ng hîp lÖ!"},
	[07] = {n_Id = {10494}, s_Desc = "Verify Client - Danh s¸ch c¸c tµi kho¶n sö dông Client kh«ng hîp lÖ!"},
	[08] = {n_Id = {10493}, s_Desc = "Verify Client - Danh s¸ch c¸c tµi kho¶n sö dông Client kh«ng hîp lÖ!"},
	[09] = {n_Id = {10492}, s_Desc = "Verify Client - Danh s¸ch c¸c tµi kho¶n sö dông Client kh«ng hîp lÖ!"},
	[10] = {n_Id = {10491}, s_Desc = "Verify Client - Danh s¸ch c¸c tµi kho¶n sö dông Client kh«ng hîp lÖ!"},
	[11] = {n_Id = {10490}, s_Desc = "Verify Client - Danh s¸ch c¸c tµi kho¶n sö dông Client kh«ng hîp lÖ!"},
	
	[12] = {n_Id = {10489}, s_Desc = "XÕp h¹ng Temp - Cao thñ m«n ph¸i Thóy Yªn"},
	[13] = {n_Id = {10488}, s_Desc = "XÕp h¹ng Temp - Cao thñ m«n ph¸i Nga My"},
	[14] = {n_Id = {10487}, s_Desc = "XÕp h¹ng Temp - Cao thñ m«n ph¸i §­êng M«n"},
	[15] = {n_Id = {10486}, s_Desc = "XÕp h¹ng Temp - Cao thñ m«n ph¸i Ngò §éc"},
	[16] = {n_Id = {10485}, s_Desc = "XÕp h¹ng Temp - Cao thñ m«n ph¸i Thiªn V­¬ng"},
	[17] = {n_Id = {10484}, s_Desc = "XÕp h¹ng Temp - Cao thñ m«n ph¸i ThiÕu L©m"},
	[18] = {n_Id = {10483}, s_Desc = "XÕp h¹ng Temp - Cao thñ m«n ph¸i Vâ §ang"},
	[19] = {n_Id = {10482}, s_Desc = "XÕp h¹ng Temp - Cao thñ m«n ph¸i C«n L«n"},
	[20] = {n_Id = {10481}, s_Desc = "XÕp h¹ng Temp - Cao thñ m«n ph¸i Thiªn NhÉn"},
	[21] = {n_Id = {10480}, s_Desc = "XÕp h¹ng Temp - Cao thñ m«n ph¸i C¸i Bang"},
	
	[22] = {n_Id = {10479}, s_Desc = "Event-QuocKhanh-02_09 Giá hoa hång"},
	[23] = {n_Id = {10478}, s_Desc = "Event-QuocKhanh-02_09 Bã hoa hång"},
}

bil_StringTask = {
	[1] = {bil_nId = {10}, bil_sDesc = "L­u chuçi ký tù cÇn rao tù ®éng trªn hÖ thèng kªnh ch¸t 1"},
	[1] = {bil_nId = {9}, bil_sDesc = "L­u chuçi ký tù cÇn rao tù ®éng trªn hÖ thèng kªnh ch¸t 2"},
	[1] = {bil_nId = {8}, bil_sDesc = "L­u chuçi ký tù cÇn rao tù ®éng trªn hÖ thèng kªnh ch¸t 3"},
	[1] = {bil_nId = {7}, bil_sDesc = "L­u ®Þa chØ IP t¹m thêi cña nh©n vËt ®Õn khi tho¸t game"},
}

_bilTaskGlobalValue = {
	-- SetGlbValue(4998, GetGlbValue(4998) + 1)
	[1] = {bil_nID = {4999}, bil_sDesc = "Tæng sè ng­êi ch¬i ®ang sö dông tÝnh n¨ng tù ®éng rao b¸n kªnh ch¸t",},
}

function Bil_SetTask(TaskNo, Value)
	return callPlayerFunction(PlayerIndex, SetTask, Bil_TaskID[TaskNo].BilTaskID[1], Value)
end

function Bil_GetTask(TaskNo)
	return callPlayerFunction(PlayerIndex, GetTask, Bil_TaskID[TaskNo].BilTaskID[1])
end
